---

- hosts: all
  vars_files:
    - cis_vars.yml

  tasks:
# PRELIM WORKSPACE SETUP (NEEDED FOR CLEANUP)
  - name: check for workspace
    stat:
      path: "{{ WORKSPACE_PATH }}"
    register: sym

  - debug: { msg: "{{ sym }}" }

  - name: create workspace dir if not exist
    file:
      path: "{{ WORKSPACE_PATH }}"
      state: directory
    when: sym.stat.exists == false
    become: yes

# AUDIT
  - name: Check for Enabled Services
    command: "systemctl is-enabled {{item}}"
    with_items: "{{ DEFAULT_ENABLED_SERVICES }}"
    ignore_errors: yes
    register: DEFAULT_ENABLED_SERVICES_STATE

# CREATE/UPDATE
  - name: Generate CIS.conf module blacklist
    template:
      backup: yes
      src: templates/cis.j2
      dest: /etc/modprobe.d/cis.conf
    become: yes


  - name: Enable default CIS systemd services
    service:
      name: "{{ item }}"
      state: restarted
    with_items: "{{DEFAULT_ENABLED_SERVICES}}"
    become: yes
    ignore_errors: yes

  - name: Disable default CIS systemd services
    service:
      name: "{{ item }}"
      state: stopped
    with_items: "{{DEFAULT_DISABLED_SERVICES}}"
    become: yes
    ignore_errors: yes

# CLEANUP TEMPLATE BACKUPS

  - name: Find Ansible Backups for Cleanup
    find:
      paths: /etc/modprobe.d
      patterns: "{{ item }}"
    register: find_results
    with_items: "{{ TEMPLATE_FILES }}"

  - name: Move Template Backups from sensitive folders to
    command: "mv {{item['path'] }} {{ WORKSPACE_PATH }}"
    with_items: "{{ find_results['files'] }}"
    become: yes
    when: find_results['files'] is defined
