---

- hosts: all
  vars_files:
    - cis_vars.yml

  tasks:
# PRELIM WORKSPACE SETUP (NEEDED FOR CLEANUP)
  - name: check for workspace
    stat:
      path: "{{ WORKSPACE_PATH }}"
    register: sym

  - debug: { msg: "{{ sym }}" }

  - name: create workspace dir if not exist
    file:
      path: "{{ WORKSPACE_PATH }}"
      state: directory
    when: sym.stat.exists == false
    become: yes


# AUDIT
  - name: Check for Enabled Services
    command: "systemctl is-enabled {{item}}"
    with_items: "{{ DEFAULT_ENABLED_SERVICES }}"
    ignore_errors: yes
    register: DEFAULT_ENABLED_SERVICES_STATE



# CREATE/UPDATE
#   INSTALL PACKAGES FROM CIS_VAR INSTALL LIST
  - name: Install Basic Packages
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
    with_items: "{{ INSTALL_DEFAULT_PKGS }}"
    become: yes

#   REMOVE PACKAGES FROM CIS_VAR REMOVE LIST
  - name: Remove Problematic Packages
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=absent update_cache=yes
    with_items: "{{ REMOVE_DEFAULT_PKGS }}"
    become: yes
    ignore_errors: yes

  - name: Generate CIS.conf module blacklist
    template:
      backup: yes
      src: templates/cis.j2
      dest: /etc/modprobe.d/cis.conf
    become: yes

  - name: Generate sysctl.conf defaults
    template:
      backup: yes
      src: templates/sysctl.conf.j2
      dest: /etc/sysctl.conf
    become: yes

  - name: Configure sysctl.conf cronjob to address debian bug during reboot
    cron:
      name: "sysctl bug resolution"
      special_time: reboot
      job: "/bin/sleep 5 && /sbin/sysctl --system"
      cron_file: '/etc/crontab'
      user: root
      state: present
      disabled: "{{ DISABLE_SYSCTL_BUGFIX }}"
      backup: yes
    become: yes

  - name: Reload sysctl from config
    command: "sysctl --system"
    become: yes

  - name: Enable default CIS systemd services
    service:
      name: "{{ item }}"
      state: restarted
    with_items: "{{DEFAULT_ENABLED_SERVICES}}"
    become: yes
    ignore_errors: yes

  - name: Disable default CIS systemd services
    service:
      name: "{{ item }}"
      state: stopped
    with_items: "{{DEFAULT_DISABLED_SERVICES}}"
    become: yes
    ignore_errors: yes

  - name: Disable Prelink
    command: "prelink -ua"
    ignore_errors: yes

  - name: Set Sticky bit on world writables
    shell: "df --local -P | grep -v 'snap' | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d -perm -0002 2>/dev/null | xargs chmod a+t"
    become: yes

  - name: AIDE| first-run initialization
    command: "aideinit"
    when: AIDE_FIRSTRUN == 'yes'
    tags: test

  - name: AIDE| Configure cronjob for daily check
    cron:
      name: "daily AIDE intrusion check"
      minute: "0"
      hour: "5"
      job: "/usr/bin/aide --config /etc/aide/aide.conf --check"
      cron_file: '/etc/crontab'
      user: root
      state: present
      disabled: "{{ DISABLE_AIDE_CHECK }}"
      backup: yes
    become: yes


# BANNER WARNINGS (LEGAL) (co-depends: banner.j2)
  - name: Set motd (postlogin)
    template:
      src: templates/banner.j2
      dest: "{{ item }}"
      mode: 0644
    with_items:
     - /etc/motd
     - /etc/issue
     - /etc/issue.net
    become: yes

#  - name: Set issue (prelogin) (stubbed)
#  - name: Set issue.net (prelogin remote) (stubbed)

# Process Hardening (co-depends: task-Generate sysctl.conf defaults )
  - name: Process Hardening (disable core dumps)
    template:
      backup: yes
      src: templates/limits.conf.j2
      dest: "/etc/security/limits.conf"
      mode: 0644
    become: yes

# Update Grub boot parameters for audit
  - name: Update GRUB_CMDLINE_LINUX
    lineinfile:
      state: present
      dest: /etc/default/grub
      backrefs: yes
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.*audit)\"[^\"]+)(\".*)'
      line: '\1 audit=1\2'
    register: UPDATE_GRUB
    become: yes
    when: GRUB_ENABLE_AUDIT == 'yes'

# Update Grub boot parameters for ipv6
  - name: Update GRUB_CMDLINE_LINUX
    lineinfile:
      state: present
      dest: /etc/default/grub
      backrefs: yes
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.*ipv6)\"[^\"]+)(\".*)'
      line: '\1 ipv6.disable=1\2'
    register: UPDATE_GRUB
    when: DISABLE_IPV6 == 'yes'

# Call Grub boot parameter update (co-depends: tasks: Update GRUB_CMDLINE_LINUX)
  - name: Call Update-Grub
    command: "update-grub"
    become: yes
    when: not UPDATE_GRUB is skipped or UPDATE_GRUB is not defined



# CLEANUP TEMPLATE BACKUPS

  - name: Find Ansible Backups for Cleanup
    find:
      paths: '/etc'
      patterns: "{{ TEMPLATE_FILES }}"
      recurse: yes
    register: find_results

  - name: Move Template Backups from sensitive folders to
    command: "mv {{item['path'] }} {{ WORKSPACE_PATH }}"
    with_items: "{{ find_results['files'] }}"
    become: yes
    when: find_results['files'] is defined


#### TODO ####

# Only for XWindows/Wayland Systems

# # gdm = 644 /etc/dconf/profile/gdm
# user-db:user
# system-db:gdm
# file-db:/usr/share/gdm/greeter-dconf-defaults
#
# # banner-message-enable banner-message-text
# # /etc/dconf/db/gdm.d/*
# # banner-message-enable=true
# # banner-message-text='the message'
# # run 'dconf update'
